# Generated by Django 2.2.7 on 2019-12-24 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("day_number", models.IntegerField()),
                ("description", models.TextField()),
                ("votes", models.IntegerField(default=0)),
                ("blurb", models.TextField(null=True)),
                ("image", models.TextField(null=True)),
                (
                    "month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.Month"
                    ),
                ),
            ],
        ),
    ]
