# Generated by Django 2.2.7 on 2019-12-24 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_holiday_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="holiday", name="month",),
        migrations.DeleteModel(name="Month",),
    ]
