# Generated by Django 2.2.7 on 2019-12-24 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_auto_20191224_0437"),
    ]

    operations = [
        migrations.RemoveField(model_name="holiday", name="day_number",),
    ]
