# Generated by Django 2.2.7 on 2019-12-25 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0010_auto_20191224_1742"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserHolidayVotes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[
                            (0, "down"),
                            (1, "up"),
                            (2, "neutral_from_down"),
                            (3, "neutral_from_up"),
                            (4, "up_from_down"),
                            (5, "down_from_up"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "holiday",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.Holiday"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserCommentVotes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[
                            (0, "down"),
                            (1, "up"),
                            (2, "neutral_from_down"),
                            (3, "neutral_from_up"),
                            (4, "up_from_down"),
                            (5, "down_from_up"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.Comment"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
