# Generated by Django 2.2.7 on 2020-01-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_holiday_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotifications',
            name='notification_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
