# Generated by Django 2.2.7 on 2020-01-31 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_holiday_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='blurb',
            new_name='push',
        ),
    ]
