# Generated by Django 2.2.7 on 2020-01-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200130_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='blurb',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
