# Generated by Django 2.2.7 on 2020-02-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_holiday_blurb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='blurb',
            field=models.TextField(null=True),
        ),
    ]
