# Generated by Django 2.2.7 on 2020-02-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_auto_20200205_2155"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holiday",
            name="push",
            field=models.TextField(blank=True, null=True),
        ),
    ]
