# Generated by Django 2.2.7 on 2020-03-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200211_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='device_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
