# Generated by Django 2.2.7 on 2020-04-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200327_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
