# Generated by Django 2.2.7 on 2020-04-06 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0027_comment_reports"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="blocked_comments",
            field=models.ManyToManyField(
                related_name="blocked_comments", to="api.Comment"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="blocked_users",
            field=models.ManyToManyField(
                related_name="blocked_users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
