# Generated by Django 2.2.7 on 2020-04-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_auto_20200406_1847"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="blocked_comments",),
        migrations.AddField(
            model_name="userprofile",
            name="reported_comments",
            field=models.ManyToManyField(
                related_name="reported_comments", to="api.Comment"
            ),
        ),
    ]
