# Generated by Django 2.2.7 on 2020-04-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_auto_20200407_1038"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="confetti",
            field=models.IntegerField(default=0),
        ),
    ]
