# Generated by Django 2.2.7 on 2020-04-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_userprofile_confetti"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="platform",
            field=models.CharField(default=None, max_length=50),
        ),
    ]
