# Generated by Django 2.2.7 on 2020-04-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_auto_20200418_1647"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="platform",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
