# Generated by Django 2.2.7 on 2020-04-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_auto_20200420_1019"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="version",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
