# Generated by Django 2.2.7 on 2020-04-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_userprofile_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_launched",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
