# Generated by Django 2.2.7 on 2020-07-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_userprofile_avatar_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="edited",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
