# Generated by Django 2.2.7 on 2020-08-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_auto_20200729_1935"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="referrer",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
