# Generated by Django 2.2.7 on 2020-08-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_userprofile_referrer"),
    ]

    operations = [
        migrations.AddField(
            model_name="holiday",
            name="creator_awarded",
            field=models.BooleanField(default=False),
        ),
    ]
