# Generated by Django 2.2.7 on 2020-08-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_holiday_creator_awarded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holiday",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Will holiday appear in the app. If false, will still appear if no creator",
            ),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="blurb",
            field=models.TextField(
                help_text="Short description appearing in Holiday list", null=True
            ),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="creator_awarded",
            field=models.BooleanField(
                default=False,
                help_text="Has user already been sent a push notification and awarded confetti",
            ),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="image",
            field=models.TextField(help_text="Paste in URL to image", null=True),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="push",
            field=models.TextField(
                blank=True,
                help_text="Push notification message sent out to users",
                null=True,
            ),
        ),
    ]
