# Generated by Django 2.2.7 on 2020-08-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_auto_20200811_1528"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="device_active",
            field=models.BooleanField(default=True),
        ),
    ]
