# Generated by Django 3.1 on 2020-08-26 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0046_auto_20200821_1253"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField()),
                ("likes", models.IntegerField(default=0)),
                ("deleted", models.BooleanField(default=False)),
                ("reports", models.IntegerField(default=0)),
                ("edited", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "holiday",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.holiday"
                    ),
                ),
            ],
        ),
    ]
