# Generated by Django 3.1 on 2020-08-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
