# Generated by Django 3.1 on 2020-08-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_auto_20200827_1439"),
    ]

    operations = [
        migrations.AddField(
            model_name="holiday",
            name="uploaded_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload image from your device",
                null=True,
                upload_to="",
            ),
        ),
    ]
