# Generated by Django 3.1 on 2020-08-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_holiday_uploaded_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holiday",
            name="image",
            field=models.TextField(
                blank=True, help_text="Paste in URL to image for upload", null=True
            ),
        ),
    ]
