# Generated by Django 3.1 on 2020-09-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_auto_20200831_1302"),
    ]

    operations = [
        migrations.RenameField(model_name="post", old_name="author", new_name="user",),
    ]
