# Generated by Django 3.1 on 2020-09-11 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_userprofile_reported_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="parent_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.post",
            ),
        ),
    ]
