# Generated by Django 3.1 on 2020-09-24 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0055_post_user_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="holiday",
            name="photo_credit_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holiday_photos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
