# Generated by Django 3.1 on 2020-10-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_holiday_photo_credit_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="holiday",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional notes about this holiday", null=True
            ),
        ),
    ]
