# Generated by Django 3.1 on 2020-10-16 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0057_holiday_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment", name="likes", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="comment",
            name="user_likes",
            field=models.ManyToManyField(
                related_name="liked_comments", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
