# Generated by Django 3.1 on 2020-10-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_auto_20201016_1004"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holiday",
            name="blurb",
            field=models.TextField(
                blank=True,
                help_text="Short description appearing in Holiday list",
                null=True,
            ),
        ),
    ]
