# Generated by Django 3.1 on 2020-11-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_product_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload image from your device",
                null=True,
                upload_to="",
            ),
        ),
    ]
