# Generated by Django 3.1 on 2020-11-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_auto_20201105_1134"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(default=None, upload_to=""),
        ),
    ]
